### ISSUE TITLE
Disable edit/delete layers button

### ISSUE THREAD

**Issue by dominic-simplan** [mstahv/v-leaflet-draw#15]
Hi,

by default, the edit and delete layer buttons are displayed. Is there any way to hide them or is this currently not supported by this addon?

![Edit/Delete Layer Buttons](https://user-images.githubusercontent.com/22240239/35665072-ceb00ce6-0724-11e8-98e7-6a9d2363f30a.png)

**Comment by octavm** [comment]
Check out the new V-Leaflet-Draw version 2.0.1. Hiding of Edit and Delete buttons is now supported.

**Comment by dominic-simplan** [comment]
@octavm Nice, thanks!
