### ISSUE TITLE
Cancel button in Edit mode results in JavaScript "Uncaught TypeDef"

### ISSUE THREAD

**Issue by gheinze** [mstahv/v-leaflet-draw#7]
Hi

I noticed a JavaScript error upon clicking the "cancel" button in edit mode. I posted a description of the problem [here](https://vaadin.com/forum#!/thread/12664970) with a minimal example to reproduce.

I tried building with the head rev of v-leaflet and v-leaflet-draw and had the same error. I'm not sure if this is an issue with my usage, the v-leaflet-draw wrapper, or the underlying leaflet JavaScript library. I was getting a bit out of my realm when looking into the JavaScript. I noticed another mention of this [here](http://stackoverflow.com/questions/33877116/leaflet-draw-does-not-cancel-properly), so it may be due to usage of the underlying library.

Might this be a known issue?   If not, no worries, I don't want to waste anyone's time on this. Just wanted to do a quick sanity check.  Thanks (and thank-you also for all the tutorials and library work).

**Comment by gheinze** [comment]
I believe I can see where the error is happening, but I haven't figured out how the Connector stuff works yet. It looks like the JavaScript portion of Leaflet Draw is expecting an array of LatLng objects but is instead receiving an array with the first element being the expected array.

When layer editing is entered, `_backupLayer` function is called:

``` javascript
        _backupLayer: function(t) {
            var e = L.Util.stamp(t);
            this._uneditedLayerProps[e] || (t instanceof L.Polyline || t instanceof L.Polygon || t instanceof L.Rectangle ? this._uneditedLayerProps[e] = {
                latlngs: L.LatLngUtil.cloneLatLngs(t.getLatLngs())
            } : t instanceof L.Circle ? this._uneditedLayerProps[e] = {
                latlng: L.LatLngUtil.cloneLatLng(t.getLatLng()),
                radius: t.getRadius()
            } : t instanceof L.Marker && (this._uneditedLayerProps[e] = {
                latlng: L.LatLngUtil.cloneLatLng(t.getLatLng())
            }))
        },
```

The parameter `t` is the layer. The function `t.getLatLngs()` retrieves an array of arrays. In this specific example:

```
    t:       [Array[4]]

    t[0]:    [o.LatLng, o.LatLng, o.LatLng, o.LatLng]

    t[0][0]: o.LatLng {lat: 1, lng: 1}
    t[0][1]: o.LatLng {lat: 1, lng: 10}
    t[0][2]: o.LatLng {lat: 20, lng: 10}
    t[0][3]: o.LatLng {lat: 20, lng: 1}
```

The Java definition was:

``` java
    LPolygon fence = new LPolygon(new Point(1, 1), new Point(1, 10), new Point(20, 10), new Point(20, 1), new Point(1, 1));
```

Looking at the clone function:

``` javascript
    L.LatLngUtil = {
        cloneLatLngs: function(t) {
            for (var e = [], i = 0, o = t.length; o > i; i++)
                e.push(this.cloneLatLng(t[i]));
            return e
        },
        cloneLatLng: function(t) {
            return L.latLng(t.lat, t.lng)
        }
    },
```

Calling `cloneLatLngs`, `t` has length 1. Calling `this.cloneLatLng(t[0])` passes the parameter: 

```
[o.LatLng, o.LatLng, o.LatLng, o.LatLng]
```

But `cloneLatLng` is expecting a LatLng object, not an array. Trying to read attributes `t.lat` and `t.Lng` off of the array fails resulting in an undefined value being returned and being backed up.  Later, the restore fails trying to use this undefined value.

I can get rid of the error If I modify the layer backup function in the Leaflet javascript from:

``` javascript
latlngs: L.LatLngUtil.cloneLatLngs(t.getLatLngs())
```

to

``` javascript
latlngs: L.LatLngUtil.cloneLatLngs(t.getLatLngs()[0])
```

I'd imagine this is not actually the correct approach. Probably has something to do with the `LinearRing` stuff where a Polygon is defined as an array of arrays: the first element being the actual Polygon and the subsequent Polygons interior holes.  Either the Connector is passing all through when only the bounding Polygon is desired, or the layer backup in the JavaScript is out of date.

**Comment by mstahv** [comment]
I have completely missed this issue. Is this still a problem with the latest version?

**Comment by gheinze** [comment]
Hi

Sorry, I don't know if things are working with the latest version.  I wasn't using interior holes in my polygon, so I did the work around and ignored backing up the interior polygons. That sufficed for the project I was working on.  Thanks for getting back on  this.  -Glenn
